services:
  oilcasex-3dviewer:
    environment:
      - OILCASEX_URL=${OILCASEX_URL}
    restart: always
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - 8081:8050
