name: production 3dviewer

on:
  push:
    branches: [ "hakasia" ]
  pull_request:
    branches: [ "hakasia" ]

jobs:
  build:
    runs-on: [virtual-hakasia]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        token: ${{ secrets.PAT_KOS4V }}


    - name: Build and run Docker Compose
      working-directory: ./deploy
      run: docker-compose up --build -d
